#:kivy 1.9.1

<Dot>:
    size:10,10
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<Zen>:
    dot: hg_dot

    Label:
        font_size: 12
        center_x: root.width/2
        top: root.top - 50
        text: str(root.accelX)

    Label:
        font_size: 12
        center_x: root.width/2
        top: root.top - 100
        text: str(root.accelY)
        
    Dot:
        id: hg_dot
        center: self.parent.center
